### ISSUE TITLE
missing functions

### ISSUE THREAD

**Issue by stroma123** [SiliconLabs/video_si21xx_superset#3]
Hello

I'm trying to use additional 'testpipe' commands available through `_Si2183_L2_Get_Echoes_Info_`, `Si2183_L2_FFT_CODE` and `_Si2183_L2_Get_EQ_` macros in Si2183_L2_API.c

However, the build fails due to missing implementation of relevant functions `Si2183_L2_Get_Echoes_Info(...)`, `Si2183_L2_FFT(...)` and `Si2183_L2_Get_EQ(...)`.

Where can I find these functions?

**Comment by MarcDorval** [comment]
Those TESTPIPE functions are only useful for the purpose of building test equipment, since they may have an impact on the demodulation results (some interrupt the demodulation process), so they are provided 'as is' without any guaranty.
[Si2183_TESTPIPE_functions.zip](https://github.com/SiliconLabs/video_si21xx_superset/files/6457417/Si2183_TESTPIPE_functions.zip)
